### PR TITLE
Removes hello-world content from reference

### LINKED ISSUE #1882: Remove hello-world asset from asset ref doc in favor of discourse post
After chatting w/ @cwjohnston , we have concluded that the hello-world content in the asset reference documentation belongs in a discourse post. That post is now up here: https://discourse.sensu.io/t/the-hello-world-of-sensu-assets/1422.

### PR DESCRIPTION
**Pull request by asachs01**
## Description

Removes the content added in #1760 

## Motivation and Context

Closes #1882

### CODE REVIEW

**Comment by hillaryfraley** [comment]
Would it be a good idea to add a link to your Discourse post somewhere toward the top of assets.md?

**Comment by asachs01** [comment]
@hillaryfraley I'm not sure. @cwjohnston do you think it would be useful?

**Review by hillaryfraley — APPROVED** [review]
This all LGTM, with the only question being whether you want to add something linking to the Discourse discussion (maybe under `Examples`?). For example:

In addition to the examples below, we also offer [a "Hello World" tutorial on Discourse][34] that describes how to create an asset from a script, upload the asset to GitHub as a release, and create your own definitions to use the asset.

[34]: https://discourse.sensu.io/t/the-hello-world-of-sensu-assets/1422

**Comment by hillaryfraley** [comment]
Remove GitHub-specific parts of this content. Leave content here in the reference doc. Link to Discourse post (if you want to host on GitHub...)

**Comment by asachs01** [comment]
@hillaryfraley can you take a gander at the 5.15 changes to add content back?

**Comment by hillaryfraley** [comment]
@asachs01 done! Please let me know if you have questions about my changes or need anything else.

**Comment by asachs01** [comment]
@hillaryfraley should be g2g as content is replicated.

**Pull request merged**
