### PR TITLE
Add format examples for label and annotation env vars

### LINKED ISSUE #2419: SENSU_LABELS env var not honored by sensu-agent
Env variables for `SENSU_LABELS` and `SENSU_ANNOTATIONS` in `/etc/default/sensu-agent` are not passed through for checks.

## Expected Behavior

Adding the following into `/etc/default/sensu-agent` (same for both sensu_labels and sensu_annotations)

`SENSU_LABELS="var1=value1, var2-value2"`
or 
SENSU_LABELS="var1=value1 var2=value2"
or
``` 
...
SENSU_LABELS='var1="value1"'
SENSU_LABELS='var2="value2"'
...
```

Does not allow the agent to use var1 or var2 for  check substitution.
## Current Behavior

check command: `echo {{ .labels.var1 | default "foo" }} {{ .labels.var2 | default "bar" }}`

returns foo/bar

## Possible Solution

might be an issue with importing multiple vars 

## Steps to Reproduce (for bugs)

1.  
2.
3.
4.

## Context

unable to use multiple env vars for labels and annotations
## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):
tested on ubuntu 16.04 and centos 7.7 (RHEL 7.7)

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
- Adds formatting examples for creating labels and annotations as environment variables

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2419

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@palourde if this is correct, should it also be in the backend reference?

Also, can this be propagated back to 5.17?

**Comment by palourde** [comment]
@hillaryfraley Yes and yes!

**Review by palourde — APPROVED** [review]
👌

**Comment by hillaryfraley** [comment]
Thank you @palourde !
Would you mind looking at one of the backend references just to make sure I didn't miss anything there?

**Comment by palourde** [comment]
@hillaryfraley Looks good to me!

**Pull request merged**
