### PR TITLE
Update OIDC Okta steps to use the Okta Dev Console

### LINKED ISSUE #2307: Improve LDAP/AD/OIDC doc
### Description
We should improve our LDAP/AD/OIDC documentation to make it easier for customers to understand and apply. This topic is complex and implementation can be difficult. We should improve our LDAP/AD/OIDC doc so that customers can be successful at implementing these auth options. 

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/installation/auth/

### Expected behavior
Customers can follow our LDAP/AD/OIDC auth instructions and successfully implement the auth option they choose. The docs include helpful examples and cover troubleshooting for all errors customers are likely to encounter.

### Current behavior
Our LDAP/AD/OIDC docs could be clearer and easier to follow. We may have some errors or unclear distinctions in our docs.

### Corrections needed
- Add to documentation of possible errors for LDAP and introduce documentation for possible errors for AD (improve https://docs.sensu.io/sensu-go/latest/installation/auth/#ldap-troubleshooting at minimum)
- Resolve `person` vs `user` (explain the distinction, clarify why we use one or the other in our examples, and provide an alternative example)

### Additional context
- Discussion in #reliability slack: https://sensu.slack.com/archives/C3MHLUP46/p1585153213018200
- Person vs. user: https://stackoverflow.com/questions/53459810/difference-between-people-and-users-ou-in-active-directory

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Updates the steps for creating a new Okta app in the OIDC reference doc to use the Okta Dev Console rather than classic UI.

Still a draft WIP -- need to:
- [x] Confirm these steps will work to create an Okta login to the Sensu web UI
- [x] Confirm whether further steps should be added, like setting the Initiate Login URI (see [issue comment](https://github.com/sensu/sensu-docs/issues/2307#issuecomment-1015502152) for details)

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2307

### CODE REVIEW

**Review by asachs01 — APPROVED** [review]
👍

**Comment by hillaryfraley** [comment]
@asachs01 were you able to confirm that the dev console steps work to create an Okta login? I think I can do it with one of the skunkworks scenarios but I haven't tried it yet.

I'm also not sure where or whether the `Initiate Login URI` comes in -- given the [user's comments in the original issue](https://github.com/sensu/web/issues/334#issuecomment-684951801), it sounds like the steps we have documented worked to get Okta login working. But it also sounds like maybe the user was doing a second thing besides creating an Okta login for the web UI. The paragraph about `When I login to OKTA...` sounds like it's out of scope.

**Comment by hillaryfraley** [comment]
Update: OK I got...something working. I followed the Okta instructions as updated in this PR, and I see the Okta login option when I reload the web UI, but I can't actually log in (`This site can’t be reached 127.0.0.1 refused to connect.`) and the [OIDC provider config instructions](https://docs.sensu.io/sensu-go/latest/operations/control-access/oidc-auth/#oidc-provider-configuration) are a little confusing, maybe because they are incomplete.

**Comment by hillaryfraley** [comment]
Other docs changes needed:

- [x] In the name attribute description table under https://docs.sensu.io/sensu-go/latest/operations/control-access/oidc-auth/#oidc-metadata-attribute, specify that the name you provide here will be used in the web UI login screen - it will replace `<name>` in `SIGN-IN WITH <name>`.
- [x] For the server attribute, it's not quite clear where users should get this information. For example, in Okta general settings, there is an "Okta domain" but is that the value to use for the server? Maybe it's this [Org Authorization Server](https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server), but I'm not sure where to find that.
- [x] Do the groups_prefix and username_prefix need to include quotation marks? Do they need the colon? The examples in the description tables do not include either, but the [OIDC configuration examples](https://docs.sensu.io/sensu-go/latest/operations/control-access/oidc-auth/#oidc-configuration-examples) and the OIDC provider config instructions do seem to indicate that the colon should be included.

**Comment by hillaryfraley** [comment]
This is almost done -- I want to review again and take a look at the LDAP and AD docs to see if anything I fixed in OIDC is applicable.

**Pull request merged**
