### PR TITLE
New messaging for Core 1.x

### LINKED ISSUE #584: Rework overview copy to use monitoring event pipeline messaging
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

The documentation should describe Sensu using our new “monitoring event pipeline” messaging in a way that’s consistent with our marketing website.

## Current Behavior

The Sensu Core docs [currently describe Sensu as an infrastructure and application monitoring and telemetry solution](
https://docs.sensu.io/sensu-core/1.4/).

## Possible Solution

Use open PR against marketing website as the basis for new copy in the docs site for both Core and Enterprise landing and overview pages.

## Context

The marketing website is [being updated](
https://github.com/sensu/website/pull/241/) to use the new monitoring event pipeline messaging.

* Browser(s) and version(s): 
* OS:

### PR DESCRIPTION
**Pull request by apaskulin**
## Description

- First draft of new diagrams and messaging for Sensu Core 1.x landing page.
- Sensu 2.0 landing page content
Looking for all the feedback.

See the previews:
- https://sensu-docs-stage.herokuapp.com/sensu-core/1.4/ 
- https://sensu-docs-stage.herokuapp.com/sensu-core/2.0/

## Motivation and Context

Closes #584 

## How Has This Been Tested?

Locally via yarn

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [x] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

### CODE REVIEW

**Comment by apaskulin** [comment]
To do:
- [x] link to video

**Review by asachs01 — APPROVED** [review]
LGTM :+1:

**Review by cwjohnston — APPROVED** [review]
These changes look great to me! 🌮 🎉

**Comment by calebhailey** [comment]
This looks great! 

The only feedback I have is that it feels like the event pipeline example image is introduced with too little context. Perhaps a caption or introductory sentence along the following: 

> "The Sensu monitoring event pipeline provides all the building blocks (or monitoring primitives) for configuring monitoring workflows. For example:" 

...or something like that. 

Then :shipit: 

Great job!

**Comment by apaskulin** [comment]
That is great feedback. I've moved up "Automate your monitoring workflows..." to introduce the diagram and emphasize the relationship between the three paragraphs in the first section and the diagram.

**Pull request merged**
