### PR TITLE
Add trace to log levels in Troubleshooting guide

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
- Adds `trace` and description to log levels in Troubleshooting guide: https://docs.sensu.io/sensu-go/5.20/guides/troubleshooting/#log-levels
- Removes note about `trace` == `debug` in Sensu

## Motivation and Context
Correct troubleshooting guide

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@palourde do you know if you added the trace level before 5.17?

**Comment by palourde** [comment]
@hillaryfraley It appears it's present since 5.0.0 (it was added on Nov 23, 2018)

**Comment by hillaryfraley** [comment]
Thank you @palourde . I propagated and I think it's ready for review now.

**Review by palourde — APPROVED** [review]
:shipit:

**Pull request merged**
