### PR TITLE
Remove Go docs for 5.12

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Remove documentation for Sensu Go version 5.12 from docs.sensu.io/sensu-go

## Motivation and Context
Update docs site versions to conform to services agreement

### CODE REVIEW

**Review by cwjohnston — CHANGES_REQUESTED** [review]
I believe this PR also needs to include an update to static.json, specifically [line 34](https://github.com/sensu/sensu-docs/blob/master/static.json#L34) where the regex should be changed to `"~ ^/sensu-go/5.1[0-2]/?((?<=\/).*)?$"`

**Comment by cwjohnston** [comment]
Once static.json is included, we'll want to deploy this to Heroku staging for verification

**Comment by hillaryfraley** [comment]
yes, you're correct! Thank you.

**Comment by hillaryfraley** [comment]
Here's the branch deployed to staging: https://sensu-docs-stage.herokuapp.com/

I clicked through some links and tested that old versions and docs that don't exist in earlier versions will redirect to /latest.

I think it's worth burning one of our Moz reports to make sure. But I want to merge the guides and double-check a few link issues, then redeploy to staging so we get a clean Moz report.

**Review by cwjohnston — APPROVED** [review]

**Comment by hillaryfraley** [comment]
This looks good to me. Only 15 4xx errors!
https://docs.google.com/spreadsheets/d/1cM-7vcEKQGImeKWaM6A-9oa4ojKAlrzTD4lhehCxn7c/edit#gid=196731968

**Pull request merged**
