### PR TITLE
Corrections to secrets docs

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Adds corrections and clarifications throughout all docs that address secrets management.

## Motivation and Context
Suggestions from Todd (listed in https://docs.google.com/document/d/1ysCZgd7gf4grTLhNa4p6l1ckK9fsIgNX_h7fpGf8hXE/edit?ts=5e4d7fc4#)

### CODE REVIEW

**Review by nixwiz — APPROVED** [review]
LGTM 👍

**Comment by nixwiz** [comment]
After some discussion with engineering, I think we may need to re-think this.  Non-root tokens expire (I haven't had mine running long enough to see that).  They will probably want to recommend TLS auth instead.  So I'm going to say hold off on these changes for now.

**Comment by hillaryfraley** [comment]
@nixwiz got it. If it helps, I can remove the root token-associated changes and create an issue to resolve that question separately (if the rest of the changes are sound). Do you think that's a good idea? Or are there other questions too?

**Comment by nixwiz** [comment]
@hillaryfraley sure, let's do that (remove root token changes and track separately).

**Comment by hillaryfraley** [comment]
Root token issue is tracked in https://github.com/sensu/sensu-docs/issues/2199

**Review by nixwiz — APPROVED** [review]
LGTM 👍

**Pull request merged**
