### PR TITLE
Restore supported versions page

### LINKED ISSUE #1819: Restore versions page
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Archived versions of the documentation are available on a page listing support status of Sensu Go releases, past and present.

When viewing this page Sensu users can

* Learn which versions of Sensu Go are currently supported
* Access offline documentation artifacts (PDF) for currently both supported versions and archived versions

## Current Behavior

Such information isn't published.

## Possible Solution

Re-introduce a versions page similar to what was added in https://github.com/sensu/sensu-docs/pull/1427 and removed in https://github.com/sensu/sensu-docs/pull/1627/

## Context

We originally removed the versions page because we were not making much progress on the archived/offline documentation that was meant to live there, and the page itself added a lot of complexity to the process of adding new versions of the docs.

As we are making progress in developing capabilities to generate offline docs, we should bring this page back so that we can start sharing offline docs artifacts.

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Restores and refines supported versions page

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/1819

## Review notes and questions
I left the "Offline docs" text linked to the previous versions.
- [x] Should I create PDF copies of the offline docs to replace the links now? Or are we waiting for an update from Ryan?
- [x] Where will we host the offline docs copies? (e.g., in a folder here in the GH repo?)
- [x] Do we want to distinguish between "docs available" and "not recommended" anymore? (Maybe change all to "Offline docs available" in that column?)
- [x] Should 5.8 be switched from "Supported" when 5.14 is released?
- [x] Should we replicate this page in the Core/Enterprise/Dashboard/Uchiwa/Plugins docs?

### CODE REVIEW

**Review by cwjohnston — CHANGES_REQUESTED** [review]
Let's do a few things:
- [x] reduce the possible statuses to `Supported` and `Archived`
- [x] Move the "offline docs" column to the right side of the chart
- [x] Replace "offline docs" link text with a download icon
- [x] Describe our definition of "supported"  as it relates to [our commercial support terms](https://sensu.io/sensu-support-services)

**Comment by hillaryfraley** [comment]
@cwjohnston , what do you think about the download icon?

**Comment by hillaryfraley** [comment]
I just noticed the download icon we use on sensu.io -- thinking we should use this one in the docs too.

sensu-download-icon

**Comment by hillaryfraley** [comment]
This page will become outdated in offline docs PDFs (even if Ryan gets the `latest` links working)

**Review by cwjohnston — APPROVED** [review]

**Pull request merged**
