### PR TITLE
[WIP] Add a proxy_requests section and various fixes/updating wording.

### LINKED ISSUE #750: Guide: Using proxy requests to monitor networking devices
The Sensu Core 2.0 Monitoring External Resources guide should include a section on using proxy resources to monitor networking devices.

Content notes:

- Use `sensuctl create` (This should be `sensuctl entity create`.)

### PR DESCRIPTION
**Pull request by rgeniesse**
## Description
 #750 

## Review Instructions
Run locally with `yarn` and review.

### CODE REVIEW

**Comment by rgeniesse** [comment]
Notes from discussion on Zoom:
- The additional proxy_requests section would cause all proxy entities to pickup this check. We need a way to filter those down both as a guide and functionality for users.
- The CentoOS 6 offering for interacting with the sensu-agent is inconsistant with other Sensu docs (`sudo /etc/init.d/sensu-agent restart` vs `sudo service sensu-agent restart`. Need to make a choice so it is consistent across docs.

**Comment by apaskulin** [comment]
We should look into the `round_robin` attribute with this feature

**Comment by rgeniesse** [comment]
@cwjohnston I think this is the idea or close to it that we wanted to work to further filter proxy clients down for the checks that they execute:

```
{
  "type": "CheckConfig",
  "spec": {
    "name": "website-check",
    "command": "http_check.sh {{ .Url }}",
    "interval": 10,
    "subscriptions": ["sensu-app"],
    "organization": "default",
    "environment": "default",
    "publish": true,
    "proxy_requests": {
      "entity_attributes": ["entity.Class == 'proxy' && entity.iswebsite == 'true'"]
     }
  }
}
{
  "type": "Entity",
  "spec": {
    "class": "proxy",
    "environment": "default",
    "organization": "default",
    "id": "sensu-doc-site",
    "url": "https://docs.sensu.io",
    "iswebsite"" true"
  }
}
{
  "type": "Entity",
  "spec": {
    "class": "proxy",
    "environment": "default",
    "organization": "default",
    "id": "my-edge-router"
  }
}
```

The expected result is that the check `website-check` is only ran by the entity `sensu-doc-site`. `my-edge-router` will not run any checks as there are not any matching.

My use of `true` may be off as that might be a string and not a boolean, but the idea is there.

**Comment by apaskulin** [comment]
Closing due to content migration. Please leave all future comments on https://github.com/sensu/sensu-docs/pull/885

**Pull request closed without merging**
