### PR TITLE
Issue template: Update checklist to match labels

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Replace checklist in issue template with label requirement

## Motivation and Context
Checklist doesn't help us categorize issues as well as labels

Edit: PR now updates checklist to match labels. See Cameron's comment below.

### CODE REVIEW

**Review by cwjohnston — CHANGES_REQUESTED** [review]
I've looked into GitHub capabilities and limitations a little further, here's what I've learned.

* Only contributors and others with proper repository permissions can set labels on issues. As such, the proposed changes to our template will not be useful to the community at large.
* Our current `issue_template.md` template is now considered legacy. Github has [a new workflow for configuring issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) which will allow us to use a template per issue type, and assign labels according to the type.

**Comment by hillaryfraley** [comment]
I didn't realize that there were restrictions on who can add labels. I guess back to the checklist...

As for the legacy issue templates, I added a card to the CR board inbox for our next planning mtg: https://trello.com/c/ys9jHlyh

**Comment by hillaryfraley** [comment]
I restored the checklist format but kept the options tailored to our labels to make it easier for us to add our own labels.

I still agree we should move our templates to the new method, but this should hold us over until then.

**Comment by hillaryfraley** [comment]
Possibly superseded by https://github.com/sensu/sensu-docs/pull/2066

**Pull request closed without merging**
