### PR TITLE
6.6.0: Update etcd heartbeat interval and election timeout defaults

### LINKED ISSUE #3269: Updated etcd-election-timeout and etcd-heartbeat-interval defaults
### Description
In 6.7.0 the default values will increase for two backend flags:
etcd-election-timeout: 3000
etcd-heartbeat-interval: 300

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/#configuration-summary
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/#datastore-and-cluster-configuration-flags

### Corrections needed
Update the default values in the start --help output and the description tables for each flag.

### Additional context
https://github.com/sensu/sensu-go/issues/4368
https://github.com/sensu/sensu-go/pull/4369
Updated PR with change to 3000/300: https://github.com/sensu/sensu-go/pull/4634

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Updates default values for etcd-heartbeat-interval and etcd-election-timeout backend config flags.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/3269

### CODE REVIEW

**Review by ccressent — COMMENTED** [review]
Change looks good, but let's wait to see if/when https://github.com/sensu/sensu-go/pull/4369 gets merged because we need to investigate a failing test there.

**Comment by ccressent** [comment]
Looks like this is not going to happen in 6.5 after all: https://sumologic.slack.com/archives/C024XK35Z3Q/p1633032781116800

**Comment by hillaryfraley** [comment]
Got it, thank you @ccressent

**Comment by hillaryfraley** [comment]
Closed -- will reopen when I create the 6.6 docs set

**Pull request closed without merging**
