### PR TITLE
Add Heroku app.json

### PR DESCRIPTION
**Pull request by cwjohnston**
## Description

Adds app.json to repository root.

## Motivation and Context

In recent weeks we've been comparing Heroku and Netlify. With the merge of #2015 we have resolved some of the issues we thought would make us switch to Netlify, so we've decided to stick with Heroku.

One thing we really liked while evaluating Netlify was their deploy preview feature. Heroku has a similar capability (they call this Review Apps) but we aren't using it currently. Per the [review apps documentation](https://devcenter.heroku.com/articles/github-integration-review-apps) we need an app.json in the project.

## Review Instructions

Compare with [app.json Schema](https://devcenter.heroku.com/articles/app-json-schema).

### CODE REVIEW

**Comment by cwjohnston** [comment]
I've manually removed the buildpacks for sensu-docs-stage via Heroku dashboard UI and initiated a deployment of this branch to test the app.json.

**Comment by cwjohnston** [comment]
Staging deployment is busted. There's no script at `bin/boot` as there should be (per [Heroku docs for the upstream project](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-static)); seems like the custom buildpack isn't being run at all.

**Comment by cwjohnston** [comment]
Restoring the our fork of heroku-buildpack-static to the sensu-docs-stage config fixes the deployment. I think we can merge this and proceed with testing the preview apps.

**Review by agoddard — APPROVED** [review]
nooooice

**Pull request merged**
