### PR TITLE
Adds the ability to move to the same page as you change versions inside of Sensu products

### LINKED ISSUE #296: Changing the version on a page takes you to the root
When on a page [for example](https://docs.sensu.io/sensu-core/1.2/reference/ssl/#generate-self-signed-openssl-certificates-and-ca)

image
 When changing to a different version it does not leave you on the documentation on that page for the new version but instead takes you to the root.

Selecting 1.1 takes you [to](https://docs.sensu.io/sensu-core/1.1/)

image

What I'd like to see is to take me to [here](https://docs.sensu.io/sensu-core/1.1/reference/ssl/)

### PR DESCRIPTION
**Pull request by rgeniesse**
## Description
Closes #296 

Adds additional URL context and logic to allow for the following to work:
- When navigating from a 1.x page to another version of 1.x, (ex core 1.4 to core 1.3), it will keep you on that page instead of taking you to the landing page for Core in this example.
- When navigating from a 1.x page to a 2.x page, the URL addition does not happen as the 1.x and 2.x pages are not 1 to 1 like 1.x pages.
- When nagivagting from a 2.x page to a 1.x page, the URL addition does not happen as the 2.x and 1.x pages are not 1 to 1.

## Motivation and Context
Better user experience if they happen onto the wrong version or would like to compare versions of documents easily.

## How Has This Been Tested?
Locally with yarn and lots of navigational jumping to look for 404s.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [ ] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] All tests have passed.

### CODE REVIEW

**Comment by rgeniesse** [comment]
@dabria I've added you to this once since you originally wrote this code. Happy to go over my thought process, etc. I also have lots of questions, :-). Let me know if/when you have time to.

**Comment by cwjohnston** [comment]
We should hold off on these changes in light of proposed changes to product naming and the knock-on effects for our information architecture.

**Comment by dabria** [comment]
>- When navigating from a 1.x page to a 2.x page, the URL addition does not happen as the 1.x and 2.x pages are not 1 to 1 like 1.x pages.
>- When nagivagting from a 2.x page to a 1.x page, the URL addition does not happen as the 2.x and 1.x pages are not 1 to 1.

These were always concerns when I was building the site. I'm happy you were able to implement this, it's going to be a lot smoother navigating the site now!
😍 

I'll hold off on my approval for now due to @cwjohnston's comment, but it looks great

**Review by apaskulin — APPROVED** [review]
I'm so sorry for holding this up. This works great locally and in [staging](https://sensu-docs-stage.herokuapp.com/). We can always make additional changes later on as we start to re-organize. Thank you so much for doing this, @rgeniesse! Feel free to merge 💚 🎉 :shipit:

**Pull request merged**
