### PR TITLE
Updating tests for yaml linting and also changing to github actions

### PR DESCRIPTION
**Pull request by hillaryfraley**
I know this isn't necessarily a best practice, but this will address #1223 and also upgrades the docs to use github actions. The benefit being that we don't have to rely on Travis and the yamllinting bits are native in Github actions.

Replaces https://github.com/sensu/sensu-docs/pull/3624

### CODE REVIEW

**Comment by hillaryfraley** [comment]
2/17/22 docs inbox cleanup discussion: we will need a Python script similar to https://github.com/sensu/sensu-docs/blob/main/tests/json-validator.py to handle yaml validation. The approach with yaml lint seems like it won't work because we only want to lint the yaml within yaml-specific code tags.

**Review by hillaryfraley — COMMENTED** [review]
Here's a PR where I tried to duplicate Richie's Python code for JSON linting:

https://github.com/sensu/sensu-docs/pull/3131/files

It didn't work, but maybe I did something obviously wrong...?

**Comment by hillaryfraley** [comment]
Today I found out about https://github.com/earldouglas/codedown -- maybe this could help?

**Comment by hillaryfraley** [comment]
https://github.com/oxsecurity/megalinter

**Comment by asachs01** [comment]
I think I've got it. I need a review though.

**Pull request merged**
