### PR TITLE
Add searches API and reference documentation

### LINKED ISSUE #2336: Document Searches API
### Description
Add a doc in the API section to cover the Searches API (see saved filtered searches in dashboard section)

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Expected behavior
API docs include the Searches API

### Current behavior
No doc currently exists for the Searches API

### Corrections needed
Add Searches API doc

### Additional context
https://sensu.slack.com/archives/C60EEQFH8/p1585857154474300

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Adds searches API documentation.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2336

See https://github.com/sensu/sensu-enterprise-go/pull/874

### CODE REVIEW

**Comment by hillaryfraley** [comment]
Cameron confirmed w/Eng that we should proceed with documenting the searches API.

**Comment by hillaryfraley** [comment]
@palourde A few questions to resolve before I can continue work on this PR:

1. The DELETE and PUT endpoints do not seem to work from cURL or Postman. When I try to DELETE or PUT a specific saved search using cURL or Postman, I get the HTTP response 404 Not Found. I can create and delete saved searches directly in the web UI, but not via cURL or Postman. Is this how the API is supposed to work?

2. GET works for /searches but not for /searches/specific-search. Is it supposed to be that way?

3. I can’t update an existing saved search at all (either via cURL, Postman, or directly in the web UI). Is that as intended? is PUT actually only POST in other words?

4. For the GET /searches endpoint, seems like the limit and continue parameters do not work. Is that as intended?

**Comment by palourde** [comment]
@hillaryfraley I think it's important to understand the context of the searches API; it was meant to be managed by/via the Web UI, and exposing it via the REST API was only done so you could import/export your search queries. Therefore, I'm not particularly excited to actually document this REST API, because it means we also have to document the actual search queries, which I don't think was the goal, and UX is not particularly great because it wasn't designed to be consumed as such.

That being said, here are the answers to your questions:

1 & 2: You can manipulate an individual search query via the `http://127.0.0.1:8080/api/enterprise/searches/v1/namespaces/{namespace}/searches/{name}` path. Therefore, you can:
- GET:
```
$ curl  -H "Authorization: Key $SENSU_API_KEY" http://127.0.0.1:8080/api/enterprise/searches/v1/namespaces/default/searches/gin
```
- DELETE:
```
$ curl -X DELETE -H "Authorization: Key $SENSU_API_KEY" http://127.0.0.1:8080/api/enterprise/searches/v1/namespaces/default/searches/gin
```
- PUT:
```
$ curl -X PUT -H "Authorization: Key $SENSU_API_KEY" -H 'Content-Type: application/json' -d '{"type":"Search","api_version":"searches/v1","metadata":{"name":"gin","namespace":"default"},"spec":{"parameters":["entity:gin"],"resource":"core.v2/Event"}}' http://127.0.0.1:8080/api/enterprise/searches/v1/namespaces/default/searches/gin
```

3. I can't talk about the behavior in the Web UI, you would have to check with the James and/or Melissa, but you can update via a PUT request.

4. This API does not support pagination indeed.

**Comment by hillaryfraley** [comment]
Thanks @palourde . I understand what you are saying about the API's background and intended use.

I didn't use namespaces in the URL, so I am seeing results for all of the endpoints now. Thank you.

**Comment by hillaryfraley** [comment]
Remaining work in reference that I will complete 6/4/20:
- Complete details in spec attribute tables
- Add an example or two

**Comment by hillaryfraley** [comment]
@palourde OK I think this one is ready for review! Thank you for all of your help.

**Review by palourde — APPROVED** [review]
👍

**Pull request merged**
