### PR TITLE
Redirect shortcode

### LINKED ISSUE #87: Redirect Uchiwa product to existing site

### PR DESCRIPTION
**Pull request by dabria**
Closes #87 

Adds a redirect shortcode.

Added it to Uchiwa's section so that we will be redirected to [https://uchiwa.io/](https://uchiwa.io/)

### CODE REVIEW

**Comment by cwjohnston** [comment]
@dabria Redirect is working for me, but the current implementation means I see a mostly empty page right before being redirected. 

I know I originally described this as a need for a redirect, but if there is a way to make the link on the front page take us directly to uchiwa.io it would make for a much nicer experience in browser.

**Comment by dabria** [comment]
I can definitely do that as well

**Comment by dabria** [comment]
I've updated the dropdown to link directly to uchiwa as well as the homepage. Should be good to merge.

**Comment by grepory** [comment]
@dabria Mind fixing conflicts and merging today?

**Comment by dabria** [comment]
Rebased with master and we're good.

**Pull request merged**
