### PR TITLE
Add offline support

### LINKED ISSUE #1647: Create layout for exporting docs to PDF manually
### User stories

- As a maintainer, I can archive a past version of the docs by creating a downloadable PDF. This can be a manual process.
- As a user needing docs for a past version of Sensu, I can download a PDF with copy-and-paste-able code sample, working links, and readable styles.

### To do

Create a version of the docs that is suitable for export to PDF using Adobe Acrobat Pro's recursive output-to-PDF feature, including these considerations:

- Fonts are adjusted to work well within PDF
- Code samples are forced to wrap within text blocks instead of using a horizontal scrollbar
- Content within language toggle blocks is accessible.

### Resources
- [Test PDF generated using Adobe Acrobat Pro in May 2019](https://github.com/sensu/sensu-docs/files/3448047/full-test-reduced.pdf)
- [Meeting notes from 7/30/2019](https://docs.google.com/document/d/1AsTZAqHfO6t3_dsVM7UyqVqQ9ymTPu7332ycoCzoHgU/edit)

### PR DESCRIPTION
**Pull request by rnevius**
## Description

Adds layouts, styles, and build processes for generating offline documentation (e.g. PDFs). For now, PDFs should be generated manually via Adobe Acrobat.

Resolves #1647

## Motivation and Context

Customers would like to access Sensu docs offline and on e-reader devices.

## Review Instructions

1. Run a local hugo server with offline layouts
    ```
    yarn run server --layoutDir=offline
    ```
2. Navigate to `http://localhost:1313/` and select your product/version of choice. Note the URL of this resource.
3. Open Acrobat and File &rarr; Create &rarr; PDF from Web Page
    
    image

    image

### CODE REVIEW

**Comment by rnevius** [comment]
@cwjohnston here's an example of a generated PDF: [Sensu Go 5.13 - Sensu Docs.pdf](https://github.com/sensu/sensu-docs/files/3653430/Sensu.Go.5.13.-.Sensu.Docs.pdf)

An issue that should be apparent right away is that SVG images aren't rendered by Acrobat. We could replace these with PNGs as needed.

**Comment by hillaryfraley** [comment]
Hi @rnevius ! I'm working on trying this out -- I seem to have some trouble at the `yarn run server --layoutDir=offline` point. Here's what happens in terminal:

--------

Never mind, I needed to switch to your branch! facepalm

**Comment by rnevius** [comment]
@hillaryfraley have you switched to this branch? The `"postcss:develop"` grunt task should be processing 2 stylesheets and generating 2 sourcemaps...so it almost seems like some of the source files are missing.

**Comment by hillaryfraley** [comment]
Yes, that was it, thank you -- sorry I didn't realize it sooner.
Just PDFd 5.0!

**Comment by rnevius** [comment]
It also appears that Acrobat doesn't render/capture emoji (such as the ✅ which is used in supported platform tables).

**Pull request merged**
