### PR TITLE
Add "register your installation" message and link in docs footer

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Adds message encouraging users to register their Sensu installations and link in footer on every page of the docs.

## Motivation and Context
https://sensu.slack.com/archives/C6AF34L6R/p1575406378319900

## Review Instructions
@cwjohnston @calebhailey @bananabele This PR gives us a starting point to discuss the content and appearance of the message in the docs footer.

### CODE REVIEW

**Comment by cwjohnston** [comment]
@calebhailey @bananabele here's a screenshot from the preview deployment. WDYT?

2019-12-19 at 12 13 PM

**Comment by bananabele** [comment]
@cwjohnston I love it! it might be too big of an ask (I'm not sure what's possible formatting wise), but at some point it'd be great to include the Sensu Go gopher as part of that banner. We could swap with the Sensu mascot  🔜 when it's ready

**Comment by hillaryfraley** [comment]
I requested a copy of the Gopher image from Anna so I can update and create a new example screenshot.

Anna thinks Stacie will have the image, so I pinged her on slack.

**Comment by hillaryfraley** [comment]
I updated the footer to add the gopher image. @bananabele , @cwjohnston , and @calebhailey , wdyt?

updated-footer

**Review by cwjohnston — APPROVED** [review]

**Pull request merged**
