### PR TITLE
Start with "entity" definition

### LINKED ISSUE #1872: Add "what is a Sensu entity"
Link to page: https://docs.sensu.io/sensu-go/5.14/reference/entities/

The first word under the first heading on this page is "Agent" (i.e. "Agent entities"), which doesn't help disambiguate these concepts. Let's open this page with a definition of what a Sensu Entity is before we get into the "how".

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Start /reference/entities with definition of "entity" rather than explanation of agent entities. The definition was in the second paragraph for some reason, so I just reversed the order of the first and second paragraphs.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/1872

### CODE REVIEW

**Review by cwjohnston — APPROVED** [review]
I think this addresses the immediate need. Seems to me we could do with an explanation of proxy entities here as well.

**Comment by hillaryfraley** [comment]
@cwjohnston I added a slightly shortened definition of proxy entities in the intro, with a link to the longer subsection. wdyt?

**Comment by calebhailey** [comment]
Wow, didn't see that this was already worked on! 

One nit here: could we create a heading called "What is an entity?" as the first heading on this page (i.e. before "How do entities work?")?

**Comment by hillaryfraley** [comment]
Got it! https://github.com/sensu/sensu-docs/pull/1891

**Pull request merged**
