### PR TITLE
Update doc with postgres health checks

### PR DESCRIPTION
**Pull request by asachs01**
## Description

This PR adds instructions for monitoring PostgreSQL's health to the datastore reference.

## Motivation and Context

Incorporate a best practice to ensure that users know when postgres goes offline.

### CODE REVIEW

**Review by hillaryfraley — COMMENTED** [review]
@asachs01 I think we should instead update the check at https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-postgresql and link to that section here in the datastore reference.

**Comment by asachs01** [comment]
@hillaryfraley I feel a bit silly now. I didn't even realize that we had that doc 🤦 I'll tweak my update to point to that.

**Comment by hillaryfraley** [comment]
@asachs01 not at all! I figured there could be a reason you wanted it in the datastore reference.

**Comment by hillaryfraley** [comment]
@asachs01 moved as we discussed. If you are happy with these changes, I can propagate to all versions before merging.

**Comment by asachs01** [comment]
@hillaryfraley LGTM!

**Pull request merged**
