### PR TITLE
Initial commit of useful plugins content

### PR DESCRIPTION
**Pull request by mbbroberg**
* So many TODOs, kinda :facepalm:
* Reducing scope and avoiding overthinking the structure

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All tests have passed.

### CODE REVIEW

**Comment by mbbroberg** [comment]
Not done but had to get somewhere. Thanks for the hack sesh @jspaleta @majormoses 👋

**Comment by majormoses** [comment]
rebased to fix conflicts.

**Comment by cwjohnston** [comment]
@mbbroberg any reason we should hold off on merging this content and iterating from there?

**Comment by majormoses** [comment]
@cwjohnston I think we should merge what we have I have rebased again to fix merge conflicts.

**Comment by mbbroberg** [comment]
👋hey all - @apaskulin is going to make a few minor edits and then merge it. Thanks!

**Comment by apaskulin** [comment]
As of https://github.com/sensu/sensu-docs/pull/392/commits/76b7bec8c0d5d8e44f1fc2e43279204644f9ea06, this PR:

- Changes the plugin docs version from 2.3 to 1.0
- Adds docs for [check definition attributes](https://github.com/sensu/sensu-docs/pull/392/files#diff-e2d5338ced9d7cd07fd7de4b929ff778R284)
- Moves the [introductory content from the GSoC page](https://docs.sensu.io/plugins/2.3/gsoc/) to a new history page
- Removes the [“planned features” content](https://docs.sensu.io/plugins/2.3/roadmap/#planned-features) from the Roadmap page
- Assorted typo, link, and formatting fixes

**Comment by majormoses** [comment]
@apaskulin I think we should be moving all the content from `2.3` to `1.0` sounds like we missed some. The intent is to align the plugins docs to the major version of sensu. While this is not a perfect system it makes the most sense going forward based on having multiple languages and such going forward. The `2.3` was indicating that the docs were versioned based on the `sensu-plugin` ruby library. Versioning for these docs are kinda awkward in the first place since each plugin is versioned independently and contains its own docs and this is meant to be for more generic documentation, guides, etc.

**Comment by apaskulin** [comment]
Re-added the missing pages and updated my previous comment with the latest set of changes

**Comment by cwjohnston** [comment]
I have updated the `plugins/latest` rewrite rule in static.json to target `plugins/1.0`.

**Review by cwjohnston — APPROVED** [review]

**Comment by mbbroberg** [comment]
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏  ❤️ @cwjohnston

**Pull request merged**
