### PR TITLE
Add check subdues guide

### PR DESCRIPTION
**Pull request by palourde**
Closes https://github.com/sensu/sensu-docs/issues/337.

### CODE REVIEW

**Review by mercul3s — CHANGES_REQUESTED** [review]
This worked for me, but I would suggest adding a note about timezones here. My test server runs in UTC, and I'd need to offset the time to equate for my business hours UTC offset (-7h).

**Comment by palourde** [comment]
@mercul3s Oh yeah, totally forgot about those, good catch!

**Comment by palourde** [comment]
@mercul3s Example updated!

**Review by mercul3s — APPROVED** [review]

**Pull request merged**
