### PR TITLE
Unfurl page-specific metadata

### PR DESCRIPTION
**Pull request by apaskulin**
Slack uses page metadata to unfurl links. Currently, the docs site applies site-wide metadata, causing Slack to unfurl the same information for every page.

## Description
This PR adds page-specific metadata to provide helpful, compact unfurls. Reference: [Slack docs](https://api.slack.com/docs/message-link-unfurling#classic_unfurling)

- Use the page title as the title, move the site title to a separate field
- Where available, append the product name and version to the title
- Where available, use the page description instead of the site description
- Use a smaller image as the site logo in hopes that Slack will unfurl the image inline with the text
- Add `<meta name="twitter:card" content="summary">` to provide link preview cards on Twitter and hopefully help with inline image unfurling on Slack

## Motivation and Context
See #314

## How Has This Been Tested?

Locally, this produces the following metadata:

**sensu-core/1.4/api/aggregates/**
(single page with description)

```
<meta name="description" content="Sensu Aggregates API reference documentation.">
<meta name="twitter:card" content="summary">
<meta property="og:url" content="//localhost:1313/sensu-core/1.4/api/aggregates/">
<meta property="og:site_name" content="Sensu Docs">
<meta property="og:title" content="Aggregates API | Sensu Core 1.4">
<meta property="og:image" content="//localhost:1313/images/sensu-logo-icon-dark@128px.png">
```

**sensu-core/1.4/guides/adding-a-client/**
(single page, no description)

```
<meta name="description" content="Monitor servers, services, application health, and business KPIs. Collect and analyze custom metrics. Get notified about failures before your users do. Give your business the competitive advantage it deserves.">
<meta name="twitter:card" content="summary">
<meta property="og:url" content="//localhost:1313/sensu-core/1.4/guides/adding-a-client/">
<meta property="og:site_name" content="Sensu Docs">
<meta property="og:title" content="Adding a Client | Sensu Core 1.4">
<meta property="og:image" content="//localhost:1313/images/sensu-logo-icon-dark@128px.png">
```

**docs home page**

```
<meta name="description" content="Monitor servers, services, application health, and business KPIs. Collect and analyze custom metrics. Get notified about failures before your users do. Give your business the competitive advantage it deserves.">
<meta name="twitter:card" content="summary">
<meta property="og:url" content="//localhost:1313/">
<meta property="og:site_name" content="Sensu Docs">
<meta property="og:title" content="Sensu Documentation Home">
<meta property="og:image" content="//localhost:1313/images/sensu-logo-icon-dark@128px.png">
```

Since there's no way to test how this will unfurl in Slack, I'll be testing the results after merging this PR and iterating if necessary.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [ ] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

### CODE REVIEW

**Comment by apaskulin** [comment]
Hugo offers a wealth of [page-specific variables](https://gohugo.io/variables/page/) for this type of use case, including page summary (the first 70 words on the page), reading time, and word count. I left these out of this PR in an effort to keep unfurls brief and reduce noise, but I'm open to feedback if there's something more you'd like to see in an unfurl.

**Review by cwjohnston — APPROVED** [review]
Looks like a winner to me! I’m excited to see this in action! 🎉

**Review by dabria — APPROVED** [review]
Looks great to me as well, excited to see it in action

**Comment by apaskulin** [comment]
It works!

unfurl example

**Comment by apaskulin** [comment]
Note: Image doesn't appear in Twitter preview

twitter

**Pull request merged**
