### PR TITLE
Add keepalive flag mapping notes for keepalive-critical-timeout and keepalive-warning-timeout

### LINKED ISSUE #2795: Document pipeline event attributes corresponding to agent keepalive timeout settings.
### Description
We need to document how agent keepalive timeout settings are mapped for event attributes.

Agents map their `keepalive-warning-timeout`  to `event.check.timeout`  and keepalive-critical-timeout to `event.check.ttl` when keepalive events are generated for the Sensu backend to process.  

Impact: These event attributes can be helpful when creating time-based alert fatigue filters for agent keepalive events.

### Category
This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [X] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
Agent reference page.
Primary reference where full explanation text should be added:
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/agent/#keepalive-configuration-flags

Secondary reference, that should have a note added, pointing back to primary reference:
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/agent/#keepalive-monitoring

### Additional context
Here is the original issue report
https://github.com/sensu/sensu-go/issues/4022

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
In https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/agent/:
- In the keepalive-critical-timeout and keepalive-warning-timeout flag description tables, adds notes to specify which event.check attributes the agent maps each flag to, with links to the check definition in the event reference.
- Adds a sentence explaining the mapping usefulness in the keepalive monitoring section with a link to the keepalive configuration flags description tables

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2795

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@jspaleta I had a quick look through the monitoring-pipelines and sensu-plugins community repos and Bonsai for an asset or plugin that might already use these event attributes in an alert fatigue filter. I didn't find anything -- do you know of an existing event filter plugin or asset that we might be able to use as an example?

**Comment by hillaryfraley** [comment]
@jspaleta just following up on this -- does this do the trick, or do you know of an example we could add?

**Comment by jspaleta** [comment]
I'll construct a filter example and get back to you.   The problem with this is these settings only really apply to keepalive events. so we'd need an example specific to keepalive events.

**Comment by jspaleta** [comment]
the information here is sufficient so you dont need to wait for a filter example.

**Pull request merged**
