### PR TITLE
Change redirects in static.json from 302 to 301

### LINKED ISSUE #1118: Change 302 redirects to 301
The `latest` functionality in the docs site uses HTTP code `302` for redirects.

To do: Change redirects to use `301` to reflect best practices.

### PR DESCRIPTION
**Pull request by cwjohnston**
## Description

Modifies static.json to specify 301 HTTP response codes should be used for all redirects.

## Motivation and Context

Closes #1118 

## Review Instructions

Currently deployed in staging for testing.

### CODE REVIEW

**Comment by cwjohnston** [comment]
I've tested the following which redirected in my browser as expected:

https://sensu-docs-stage.herokuapp.com/sensu-go/latest/
https://sensu-docs-stage.herokuapp.com/sensu-core/latest/
https://sensu-docs-stage.herokuapp.com/sensu-core/2.0/
https://sensu-docs-stage.herokuapp.com/sensu-enterprise/latest/

But curl still shows 302 responses from nginx:

```
$ curl -si https://sensu-docs-stage.herokuapp.com/sensu-core/latest/
HTTP/1.1 302 Moved Temporarily
```

**Comment by cwjohnston** [comment]
I am expecting the template logic here to be exercised every time we deploy: https://github.com/sensu/heroku-buildpack-static/blob/master/scripts/config/templates/nginx.conf.erb

**Comment by cwjohnston** [comment]
Turns out I did not push the correct branch to staging. Looks better now:

```
curl -si https://sensu-docs-stage.herokuapp.com/sensu-core/latest/
HTTP/1.1 301 Moved Permanently
```

**Review by apaskulin — APPROVED** [review]
Ran `curl -si https://sensu-docs-stage.herokuapp.com/sensu-core/latest/` and got 301 🎉 Thanks, @cwj!

**Pull request merged**
