### PR TITLE
Enterprise 3.0 changelog

### PR DESCRIPTION
**Pull request by cwjohnston**
## Description

Add Enterprise 3.0 content to changelog

## Motivation and Context

Keeps the changelog up to date

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [X] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

### CODE REVIEW

**Review by apaskulin — COMMENTED** [review]
LGTM! Do we need to mention the change to `overwrite_quiet_hours`?

**Comment by cwjohnston** [comment]
@apaskulin good idea, added description of `overwrite_quiet_hours` change in latest commit

**Review by apaskulin — APPROVED** [review]
🎉 :shipit:

I added a minor revision to the `overwrite_quiet_hours` fix here: https://github.com/sensu/sensu-docs/pull/467/commits/31edb116f63451c465cf9df9d167b3fb91e7dd3a

**Comment by cwjohnston** [comment]
@amdprophet anything missing here so far?

**Comment by amdprophet** [comment]
Contact names are now logged from any log messages generated within integrations.

**Comment by amdprophet** [comment]
Looks good!

**Review by amdprophet — APPROVED** [review]

**Comment by amdprophet** [comment]
Ship it! 👍

**Review by apaskulin — APPROVED** [review]
🌟 :shipit:

**Pull request merged**
