### PR TITLE
Enterprise/add/using ec2

### LINKED ISSUE #378: Guide Wanted: Using the EC2 integration w/ SE
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)

## Expected Behavior
Have a guide that elaborates on how to use the EC2 integration both with and without IAM roles.

## Current Behavior
There isn't a guide that describes this.

### PR DESCRIPTION
**Pull request by asachs01**
## Description
Creates a guide for using the EC2 up to version 2.8

## Motivation and Context
Quite a few SE customers have asked about how to use the EC2 guide, and this fulfills that inquiry to deflect support requests. Closes #378

## How Has This Been Tested?
`yarn server`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New doc/guide
- [ ] Fixing errata
- [ ] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

### CODE REVIEW

**Comment by asachs01** [comment]
Closes #378

**Comment by cwjohnston** [comment]
I think we can provide more detail on the IAM instance role implementation. Here are my notes:

Here are the steps to do so:

1. Create an IAM permission policy like so:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["ec2:DescribeInstances"],
      "Resource": ["*"]
    }
  ]
}
```
2. Create an IAM trust policy like so:
```
{
  "Version": "2012-10-17",
  "Statement":[
    {
      "Action": "sts:AssumeRole",
      "Principal": {
      "Service": "ec2.amazonaws.com"
    },
    "Effect": "Allow",
    "Sid": ""
    }
  ]
}
```

3. Create an EC2 instance role
4. Associate the IAM policies created in #1 and #2 with the EC2 instance role created in #2
5. Attach the EC2 instance role to your Sensu Enterprise instance(s)
6. Ensure Enterprise instance is configured with appropriate ec2 config attributes, restart service if necessary.

**Comment by asachs01** [comment]
@cwjohnston I cant get the trust policy to create. 

```
This policy contains the following error: Has prohibited field Principal For more information about the IAM policy grammar, see AWS IAM Policies
```

I'm still digging into it, but it might be that we have to do this slightly differently.

**Review by cwjohnston — CHANGES_REQUESTED** [review]
Images aren’t showing up for me in yarn server. Anyone else having this problem?

I’m thinking the images belong in the `guides` directory so they are versioned with the guide.

**Comment by asachs01** [comment]
@cwjohnston images should be in there as of 1 hour ago. We've not versioned the images yet in Enterprise, and I don't think we've done that in the Enterprise Dashboard portion either.

**Comment by cwjohnston** [comment]
I guess my local branch wasn’t up-to-date, I am now seeing the images.

I think we can go ahead and merge this as is. My belief is that if we update this guide to describe cross-account IAM role feature in 3.1, the guide wil become long/complex enough that we should opt to use aws-cli commands instead of screenshots for describing the needed IAM roles/policies.

**Review by cwjohnston — APPROVED** [review]
I rescind my request for versioned images.

**Pull request merged**
