### PR TITLE
Add supported OS versions for binary distributions

### LINKED ISSUE #2699: Specify minimum required platform versions for binary distributions
### Description
Docs do not specify the minimum required versions for each platform to run Sensu binaries.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/platforms/#binary-only-distributions

### Expected behavior
Docs specify the minimum required version for each platform to run Sensu binary distributions.

### Current behavior
Docs do not specify minimum required versions for binary distributions.

### Corrections needed
Add minimum versions required for each platform:
- Solaris 11 or above, amd64 only (not sparc)
- Windows Server 2008R2 and above, Windows 7 and above
- macOS 10.11 and above
- FreeBSD 11.2 and above

For Linux, list https://github.com/golang/go/wiki/MinimumRequirements#linux and explain we support kernel 2.6.23

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Adds supported OS version information for all binary distributions.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2699

### CODE REVIEW

**Comment by hillaryfraley** [comment]
A couple points to clarify:

1. The info at https://github.com/golang/go/wiki/MinimumRequirements#linux isn't very clear in terms of what caveats it describes or what the dependencies are for each architecture, so I did not link it in the doc. I think it would be better to explain what we do and don't support for each architecture explicitly in our documentation.
2. I may have misunderstood this, but I interpreted [Eric's comment](https://sensu.slack.com/archives/C60EEQFH8/p1598905793252300?thread_ts=1598903089.246400&cid=C60EEQFH8) to mean that we support one kernel for AMD and ARM architectures and a different kernel for the rest of the architectures. If I misinterpreted this, please let me know.

**Comment by amdprophet** [comment]
1. I think that's ok.
2. I think requirements should be as so:
ARMv5 requires Linux kernel 3.1.x or later.
MIPS64LE requires Linux kernel 4.8 or later.
Everything else requires Linux kernel 2.6.23 or later.

**Comment by hillaryfraley** [comment]
@amdprophet thank you! I updated the list for Linux.

Final question: do these same OS requirements apply for 5.19, 5.20, and 5.21 as well?

**Review by amdprophet — APPROVED** [review]

**Comment by amdprophet** [comment]
@hillaryfraley yup!

**Pull request merged**
