### PR TITLE
Archive versions 5.0 through 5.11 and update static.json

### PR DESCRIPTION
**Pull request by hillaryfraley**
Replaces https://github.com/sensu/sensu-docs/pull/1875
Adds changes to static.json to redirect 5.0-5.11 to /latest

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@cwjohnston I think this fixes the issue with trying to access earlier versions! Links with ../ and ../../ also seem to work.

If I try https://deploy-preview-1893--sensu-docs.netlify.com/sensu-go/5.5, it redirects to https://deploy-preview-1893--sensu-docs.netlify.com/sensu-go/latest. So far, so good.

But when I click any of the links in the first or third paragraphs on https://deploy-preview-1893--sensu-docs.netlify.com/sensu-go/latest, I get a 404.
Try those links from https://deploy-preview-1893--sensu-docs.netlify.com/sensu-go/5.14/ though, and they all work.

I think the problem may be that for some reason on that page, the relative links do not use ../ or ../../
Here are the links for the third paragraph:
`**Automate your monitoring workflows**: Limitless pipelines let you validate and correlate events, [mutate data formats][20], [send alerts][21], manage incidents, [collect and store metrics][22], and more.`
```
[20]: guides/extract-metrics-with-checks
[21]: guides/send-slack-alerts/
[22]: guides/influx-db-metric-handler/
```

I'm guessing these are leftover from earlier versions where we were linking to docs in the same content folder in the same repo.

I was thinking to test, I should git checkout this branch, change the links in 5.14 index.md to use ../../, and commit. That should re-run the Netlify deploy and get us a new staging site to test, right?

**Comment by cwjohnston** [comment]
I think I've solved for those broken index page links by prepending them with `./`

For ease of review, I added the changed for each version's index in separate commits.

**Comment by cwjohnston** [comment]
This blog post suggests a JavaScript snippet to rewrite URLs with `/` appended. I’ve added it to the footer_js partial.

**Comment by hillaryfraley** [comment]
Dropped Moz report in #reliability channel in Slack.

Looks like redirects aren't working for previous versions. For example: http://deploy-preview-1893--sensu-docs.netlify.com/sensu-go/5.14/guides/use-apikey-feature/ doesn't work b/c there is no API key guide for 5.14.

**Comment by cwjohnston** [comment]
Because the javascript redirect approach does not seem to help with our 404 test reports, I've revered that commit and reached out to Netlify support for their suggestions.

**Pull request closed without merging**
