### PR TITLE
Add floating table of contents

### PR DESCRIPTION
**Pull request by rnevius**
## Description

As above. In order to accomplish this, I have completely removed the defunct/mostly unused hugo-material-docs theme, and upgraded Hugo to v0.70.0 for Goldmark and `.TableOfContents` support.

Updates https://github.com/sensu/sensu-docs/issues/2443#issuecomment-628191413

## Motivation and Context

https://github.com/sensu/sensu-docs/issues/2443#issuecomment-628191413

## Review Instructions

I'm not in love with the style...but it could just be me. Part of the issue is that Sensu Docs headings are quite long (compared to something like the [Grafana docs](https://grafana.com/docs/grafana/latest/installation/requirements/)). Maybe things will look cleaner with shorter headings.

It's also possible that the `startLevel`/`endLevel` in the `tableOfContents` configuration need to be modified.

### CODE REVIEW

**Review by hillaryfraley — CHANGES_REQUESTED** [review]
@rnevius I like the look although I see what you mean about longer headings on the page. I think we can reduce or eliminate the number of pages with unwieldy H2 lengths if I rewrite the headings in the API docs. I also noticed a couple pages with zero on-page headings, which makes the empty right-side menu look strange :D I am sure those pages need a heading or two.

One potential issue: it looks like there is something weird happening on pages that contain a highlighted shell code block. Maybe the content in those blocks isn't wrapping?

I'm seeing it on these pages:
- https://docs.sensu.io/sensu-go/latest/getting-started/prometheus-metrics/
- https://docs.sensu.io/sensu-go/latest/guides/enrich-events-with-hooks/
- https://docs.sensu.io/sensu-go/latest/reference/datastore/

It may be happening on other pages too -- I just tried to confirm it's not isolated to a single page.

**Comment by hillaryfraley** [comment]
Here's a gif that shows the issue I mentioned:

right-side-menu

**Comment by rnevius** [comment]
@hillaryfraley nice catch. This bug has been fixed.

**Comment by hillaryfraley** [comment]
@rnevius We are wondering if it's possible to make a few adjustments:

1. Can the floating TOC have an indicator of the user's place on the page? For example, as they scroll down, can the current section displayed on the page be highlighted in some way in the floating TOC? This is the most important adjustment we'd like to make.

2. [HOLD] see https://github.com/sensu/sensu-docs/issues/2474 When a user clicks on one of the H2 headings in the floating TOC, can that H2 heading expand in the floating TOC to list the H3 headings it contains?

3. Can we evenly adjust the line spacing all H2 and H3 headings? I tested `endLevel = 3` in `[markup.tableOfContents]`, and the first H3 heading was closer to the bottom of the H2 heading than it was to the next H3 heading.

**Comment by rnevius** [comment]
@hillaryfraley I have updated items (1) and (3) from your previous comment. Item (2) is a little more tricky (not impossible). Can you take a look at the new state of things and let me know if this is something you'd still like to pursue?

**Comment by hillaryfraley** [comment]
@rnevius thank you! We have a couple changes to request, but I will add them in a review comment.

We want to hold on item 2 (expanding H2 when clicked to list all H3 the H2 contains) for now. I can create a new issue so that it's documented and ready to assign when we're ready to add that piece.

**Review by hillaryfraley — CHANGES_REQUESTED** [review]
@rnevius I think this looks great as usual, although we'd like to request a couple changes.

1. Green text color change:
  - If the user does not click any heading in the floating TOC and only scrolls down the page, apply the green text color change only to the top-most heading on the page as they scroll down instead of highlighting all headings currently shown on the page
  - If the user clicks a heading in the floating TOC, apply the green text color change only to the heading the user clicked (even if the page layout makes it so there is another heading above it at the top of the page)

2. Arrows:
- Do not use arrows if the user only scrolls down the page without clicking a heading in the floating TOC
- If the user clicks a heading in the floating TOC, use the arrow (along with the green text color change) to indicate the heading the user clicked

Please let me know if these aren't clear or will present a problem! And thank you again.

**Comment by hillaryfraley** [comment]
Hi @rnevius I just wanted to follow up on my previous comment about changes to the green text color and arrows. Are these adjustments possible?

**Comment by hillaryfraley** [comment]
Hi @rnevius -- I'm following up again. Is it possible to make the adjustments described in https://github.com/sensu/sensu-docs/pull/2466#pullrequestreview-416486847?

**Comment by rnevius** [comment]
@hillaryfraley yes, these changes are in progress. I will send an update to this PR and request another review ASAP today or tomorrow.

**Comment by rnevius** [comment]
@hillaryfraley I _think_ I have implemented things as requested. Please let me know if I've misunderstood, or if something needs to be updated.

**Comment by hillaryfraley** [comment]
@rnevius thank you! This looks great overall. I'm excited that we are close to merging this one!

There are a couple things I didn't notice before:

1. The floating TOC highlighting isn't working on the release notes page (the links in the floating TOC work, but the current section never highlights in green).
  - Possibly related: the manual links at the top of the page stopped working. I plan to remove these manual top-of-page TOCs as soon as we merge this PR, so I only mention it in case it's an issue you need to be aware of. edit: The manual top-of-page TOCs do still work on other pages, so I think this issue is limited to the release notes page.

2. Images are not displaying on some pages (for example, the images at https://docs.sensu.io/sensu-go/latest/dashboard/overview/ do not display in the review app at https://sensu-docs-feature-navi-hfj593.herokuapp.com/sensu-go/latest/dashboard/overview/). This may be because those dashboard overview images are in a div -- the images in https://docs.sensu.io/sensu-go/latest/guides/deploying/ are inside a figure shortcode, that might be why they display in the review app (https://sensu-docs-feature-navi-hfj593.herokuapp.com/sensu-go/latest/guides/deploying/) and the images in the dashboard overview do not. I can move all of our images into the figure shortcode if that will solve the problem.

And one other change:

3. If I click a heading in the floating TOC, it adds the arrow and highlighting as we requested, but the arrow and highlighting do not change as I scroll back up the page. I described the request poorly in the the second bullet point under request 1 in my previous comment. My intent was that if someone clicked a heading in the floating TOC, the TOC arrow/highlighting would indicate the section they clicked even if there was more than 1 section on the page at the time. But if someone scrolls back up after clicking, I would like the TOC to go back to highlighting the top-most heading on the page at the time. I think I'm making things too complicated with the arrow indicating one thing and the highlighting indicating another. Can you make these changes:
  - If someone clicks a section in the floating TOC, use the arrow and highlighting to indicate the section clicked.
  - If someone clicks a section in the floating TOC and then scrolls around, use the arrow and highlighting to indicate the top-most heading on the page at the time (so the arrow and highlighting starts with the section they clicked but would change as they scroll if they leave that section).
  - If someone scrolls without clicking any particular section in the floating TOC, use the arrow and highlighting to indicate the top-most heading on the page at the time.

We want to have the arrow in addition to the highlighting to indicate position on the page to help make that clear even if a reader can't distinguish between the green and blue.

Does this make sense? Please let me know if it does not.

Edit: I discovered another thing -- `yarn run server --layoutDir=offline` doesn't seem to work on this branch (although the error references sensu-core):
```
hillaryfraley@Hillarys-Sensu-MacBook-Pro sensu-docs % yarn run server --layoutDir=offline
yarn run v1.19.1
$ grunt server --layoutDir=offline
Running "env:dev" (env) task

Running "env:dev" (env) task

Running "print-hugo-version" task
Hugo Static Site Generator v0.72.0-8A7EF3CF darwin/amd64 BuildDate: 2020-05-31T12:07:44Z

Running "sass:develop" (sass) task

Running "postcss:develop" (postcss) task
>> 2 processed stylesheets created.
>> 2 sourcemaps created.

Running "concurrent:target" (concurrent) task
    Running "watch" task
    Running "hugo-server" task
    Running Hugo server
    Waiting...
    Building sites … Built in 990 ms
    Error: Error building site: "/Users/hillaryfraley/sensu-docs/content/sensu-core/0.29/faq.md:21:24": failed to extract shortcode: template for shortcode "check" not found
    Fatal error: Error
Warning: Error: Error building site: "/Users/hillaryfraley/sensu-docs/content/sensu-core/0.29/faq.md:21:24": failed to extract shortcode: template for shortcode "check" not found Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rnevius** [comment]
> the manual links at the top of the page stopped working...The manual top-of-page TOCs do still work on other pages, so I think this issue is limited to the release notes page.

This is actually a result of the IDs for these sections being invalid (because they start with a number). This caused a lot of problems with the Table of Contents (especially for `h3` elements, which often are part of lists that start with a number). I've had to actually modify the ID attributes via JS in order to support the scroll/interaction observer and ToC link clicking. 

I'll rework things so that modifying the ID attribute for a section also modifies it in the top-of-page contents area.

**Comment by hillaryfraley** [comment]
@rnevius I may be misunderstanding or not have the whole picture-- we're going to remove those top-of-page TOCs as soon as the floating TOC is 👍 and merged, so I don't think they need to work because they won't coexist with the floating TOC (at least I'm going to get rid of them as soon as I can once this PR is merged)

**Comment by rnevius** [comment]
@hillaryfraley I made another batch of changes. Please let me know if there's anything amiss.

**Comment by hillaryfraley** [comment]
1 of 2

@rnevius thank you! Just one thing, still to do with the release notes page. I know it's impossible to fit the entire list of headings onto a single page, but the release notes floating TOC doesn't scroll along with the page. Even if I click the last TOC entry I can see, the page doesn't jump down or scroll so I can see later entries.

Here's a gif to show you what I'm seeing:

release-notes-floating-toc

edit: wow these gifs are difficult to look at, squashed together in one comment. I'll move the TOC one down to a separate comment.

**Comment by hillaryfraley** [comment]
2 of 2

Is it possible to have the TOC on the release notes page work more like the TOC on the FAQs? Here's another gif (hopefully it shows how it's working differently):

faq-floating-toc

**Comment by rnevius** [comment]
@hillaryfraley The ToC behavior is actually consistent between all pages. The FAQ works the way it does because the content (by chance) happens to match perfectly with the ToC list items. The ToC is sticky to the top of the page until the site footer "bumps" into it, at which point it's pushed up. This also happens on the Release Notes page...but the page content is a lot longer than the FAQ, so it takes longer for it to happen. 

I'm not really sure how to best resolve this issue – where the ToC is longer than the height of the page, but the page content is so long that the ToC isn't bumped up "soon enough". 

If we add scroll functionality to the ToC, then a user could be confused if they try to scroll the main content with the cursor focused in the ToC. I suppose that we could try to somehow automatically adjust the vertical positioning of the ToC as a user scrolls; this would have to be synced to the scrolled % of the content. A potential problem with that is that the top and bottom of the ToC would be clipped when a user is in the middle of a long page with a lot of headings. 

Thoughts?

**Comment by hillaryfraley** [comment]
@rnevius thank you for explaining. What do you think about creating a page-level frontmatter attribute that would turn off the floating TOC? In other words, like the `offline:` attribute we add to pages that we don't want to appear in the offline layout.

We could use the attribute I'm suggesting for any page has too many headings for the floating TOC to work the way we want. On such pages, I would retain the manual TOC at the top of the page, since the attribute would prevent the floating TOC from appearing.

Currently the release notes is the only page I'm aware of that presents this problem, so this seems like the least disruptive solution. Of course, I say this without knowing how difficult it is to create the attribute I'm suggesting.

**Comment by rnevius** [comment]
@hillaryfraley that's a good idea and easy to implement. I'll work on it!

**Comment by rnevius** [comment]
@hillaryfraley this functionality has been added. As a test, I have added the `toc: false` page param to /sensu-go/5.20/release-notes

**Review by hillaryfraley — APPROVED** [review]
@rnevius This is great! Thank you for all of your work.

I won't merge until Monday because I have a little bit of work to do with removing the manual TOCs from the tops of pages. But I think this one is 👍 💯

**Review by hillaryfraley — CHANGES_REQUESTED** [review]
@rnevius I'm sorry to backtrack on this. I just discovered that the `offline: false` frontmatter attribute doesn't seem to be working now. When I run `yarn run server --layoutDir=offline` and open a local copy in my browser, I see the Supported Versions page (which should be excluded using `offline: false`).

edit: I pushed a commit to this branch without thinking. It's changes we'll want anyway (propagating the toc frontmatter attribute to all release notes) but it seems to be interfering with updating this branch against the base.

**Comment by rnevius** [comment]
@hillaryfraley ready for another review. The last couple of issues have been a result of different behavior with the new version of Hugo in this PR. Nice QA.

**Review by hillaryfraley — APPROVED** [review]
@rnevius thank you for resolving everything I found! This looks great. I'm going to merge it today 🎉

**Pull request merged**
