### PR TITLE
Add script for creating a new version of docs

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Adds a script for completing steps in https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#add-a-docs-version.

## Motivation and Context
Make https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#add-a-docs-version process less manual.

## Review Instructions

**Confirmed 6/23/20**: Currently accomplishes step 2 in the https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#add-a-docs-version process.

To confirm this iteration:
1. Manually complete step 1 at https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#add-a-docs-version
2. Use this command to confirm it updates everything in step 2:
```
./scripts/new-docs-version.sh 'version: "5.20"' 'sensu-go-5.20:' 'menu: "sensu-go-5.20"' 5.20 'version: "5.21"' 'sensu-go-5.21:' 'menu: "sensu-go-5.21"' 5.21
```

Next iteration: automate step 1 at https://github.com/sensu/sensu-docs/wiki/Add-a-version (create dir for new docs version, copy previous docs version into new dir, and make sure step 2 still works).

### CODE REVIEW

**Comment by hillaryfraley** [comment]
This does programmatically accomplish step 2 at https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#add-a-docs-version!

**Comment by cwjohnston** [comment]
@hillaryfraley I updated the script with a version that's working locally for me.  Will you give it a shot and let me know what you think?

**Comment by hillaryfraley** [comment]
@cwjohnston I added a couple lines in this.

1. If I provided an invalid OLD_SENSU_VERSION like `./scripts/new-docs-version.sh '5.25' '6.0'` the responses would say there isn't a 5.20 and the script would do nothing but would still print the "job done" response. So I added something in the `check_args` function to evaluate whether the OLD_SENSU_VERSION variable was an existing directory and to terminate with an error message if not. At least, I *think* that's what I did 😅  It seems to be working.

2. In the `find_and_replace` function, the line `find "$DOCS_ROOT/content/sensu-go/$NEW_SENSU_VERSION" -iname '*.md' -exec sed -i "s/  sensu-go-${OLD_SENSU_VERSION}\:/  sensu-go-${NEW_SENSU_VERSION}\:/g" {} +` would not work for the menu frontmatter item in top-level docs (I think b/c it is formatted like `menu: "sensu-go-5.21"` instead of having the menu value on a separate line without quotes and with two spaces). I tried to just remove the two spaces after `s/` in this line, but that didn't work. So I added a second line in the `find_and_replace` function to cover instances of `menu: "sensu-go-5.21"`. There is probably a more elegant way to do it but again this seems to work.

What do you think of these changes? I'm really excited that this script is actually creating a new docset. Thank you.

**Review by cwjohnston — APPROVED** [review]
LGTM! 👍

**Pull request merged**
