### PR TITLE
Update instructions for creating an OIDC app

### LINKED ISSUE #2647: Okta OIDC instructions need update
### Description

It seems Okta UI has changed, so our instructions don't help as much as we'd like.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/

### Expected behavior

Documented instructions are usable.

### Current behavior

Documented instructions reference settings/sections no longer present in Okta UI.

### Screenshots

2020-07-24 at 2 00 PM

### Additional context

Ideally we'd figure out how to reduce coupling with Okta or any other provider such that users have enough context from us to follow their provider's instructions.

* Browser(s) and version(s): 
* OS:

### LINKED ISSUE #2700: Update the instructions for the Okta application creation
### Description
It appears that the Okta interface was either modified or we forgot to mention an important step in our docs (https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/#create-an-okta-application).

1. We need to add a step after `4.`, before the user saves the config. They will need to check the following box, in order to allow Sensu to refresh the access token:
Screen Shot 2020-08-31 at 4 22 16 PM
2. Steps `6.`, `7.` & `8.` no longer appear to be relevant: These configuration no longer appear in the Okta interface. I believe we can safely remove those two instructions:
Screen Shot 2020-08-31 at 4 29 52 PM

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/#create-an-okta-application

### Additional context

* Browser(s) and version(s): 
* OS:

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Description
Updates instructions for creating an OIDC app at https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/#create-an-okta-application

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2700
Closes https://github.com/sensu/sensu-docs/issues/2647

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@palourde a couple questions:

1. It looks like your screenshot includes information that we don't instruct users to enter. For example, in your screenshot there is a Base URI and a Logout redirect URI. Our instructions do not tell users to enter these -- should we add that step?
2. The last step in our instructions is `Assign people and groups in the Assignments page.` In your screenshot, it looks like there is a field for adding group assignments right in the Application Settings window (it says "Everyone"). Should we tell users to add group assignments there and end our instructions with telling them to save?

**Comment by palourde** [comment]
1. Actually that would replace step 4., and now I'm realizing that this step is wrong; it should be `{API_URL}`, not `{DASHBOARD_URL}`; Same goes for the URL in the `OIDC provider configuration` section.

We can tell users to ignore the logout redirect URI for now.

2. They can actually do it both ways, not sure which one is preferable though.

**Comment by hillaryfraley** [comment]
@palourde thank you! I updated the PR with your feedback. Wdyt?

Do these instructions apply for all published docs versions (5.19-6.0)? If so, I will propagate the changes after the PR is 👍

**Comment by palourde** [comment]
As discussed, I was actually wrong because the instructions I provided were for the developer console of Okta, not the "Classsic UI".

If we take back the original instructions, here are the updates we need:

- Use API_URL instead of DASHBOARD_URL
- After step 5 (`Click Save`), we need to instruct users to edit the general settings in order to add the `Refresh Token` as an allowed grant types:




The rest of the instructions were actually correct. Also, to answer your last question, yes these updated instructions would apply to all published docs versions.

Thank you again and sorry for the inconvenience.

**Comment by hillaryfraley** [comment]
Thanks for all the screenshot support today, @palourde :D I think this is really ready for your review now.

**Review by palourde — APPROVED** [review]
Successfully tested these instructions!

**Pull request merged**
