### PR TITLE
Update client-to-server transport documentation

### PR DESCRIPTION
**Pull request by gattie**
## Description

The example yaml file under the *Client-to-server transport security with HTTPS* section in the clustering guide says to use the client.pem and client-key.pem files. However, this fails to work and are not the correct certs and keys to use in this location. Instead, you should use the specific backend cert and keys you generated in the previous step.

## Motivation and Context

This change is required because currently the provided solution in the documentation leads users down a path that will fail. The change provided in this PR should direct users to utilize the correct certs and keys.

### CODE REVIEW

**Comment by rgeniesse** [comment]
Thanks for the PR @gattie! I have a vagrant setup I am going to run this through to confirm/update my tests, but based on the Slack conversation it sounds like you and other users have ran into the same issue.

**Comment by gattie** [comment]
@rgeniesse your updates look good from my perspective. I think that addresses the issue of which certs and keys to use as well as providing an example config for each backend in the cluster 👍

**Comment by rgeniesse** [comment]
Thanks @gattie. I've added them as agents connected to the cluster should have each backend in its configuration.

I'll copy to 5.1.

**Review by rgeniesse — APPROVED** [review]
I'll merge once PR CI comes back. For whatever reason, branch isn't working. Might be some new travis.com integration and forked repo weirdness.

**Pull request merged**
