### PR TITLE
Add support for multi-level navigation nesting

### PR DESCRIPTION
**Pull request by rnevius**
## Description

Adds support for an additional level of menus/content nesting:

image

## Motivation and Context

Updates #2443 (resolves item #1)

## Review Instructions

To add additional levels of content (for example, at `https://docs.sensu.io/sensu-go/latest/sensuctl/reference/`), the process is similar to how we currently create menu items:

1. Create a new directory:

        content/sensu-go/5.21/sensuctl/reference

2. Create a top-level `_index.md` page in that directory, with front matter similar to the following. The important keys are `title`, `version`, and `menu`. The `menu` key must include both a `parent` (which it is to be nested under) and an `identifier` (which its child items will use):

        ---
        title: "Nested Reference Menu"
        description: "Nested menu description"
        weight: 70
        product: "Sensu Go"
        version: "5.21"
        layout: "base-for-directory-listing"
        menu:
          sensu-go-5.21:
            parent: sensuctl
            identifier: sensuctl-reference
        ---
        
        {{< directoryListing >}}

3. Create any number of child pages in the same directory (for example, `content/sensu-go/5.21/sensuctl/reference/subpage.md`), with front matter that includes the following:

        menu:
          sensu-go-5.21:
            parent: sensuctl-reference

Please let me know if you have any questions.

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@rnevius thank you!

I can't seem to get the sub-menu item to act like a menu (with the dropdown arrow, for example). I followed the instructions and created a "testing" sub-menu with two test pages. Here's what happens when I place this folder inside or outside the "sensuctl" top-level menu item.

Inside:
test-nested-menu-inside-sensuctl


Outside:
test-nested-menu-outside-sensuctl

This is partly where we want to end up after completing item 2 in https://github.com/sensu/sensu-docs/issues/2443: clicking on any menu item (top-level or sub-menu) will open its own page *and* will list any sub-pages nested under the menu item (again top-level or sub-menu). Would it be easier to combine items 1 and 2 in https://github.com/sensu/sensu-docs/issues/2443?

**Review by hillaryfraley — CHANGES_REQUESTED** [review]
See my comment https://github.com/sensu/sensu-docs/pull/2561#issuecomment-647560983.

I might be missing a step, but I don't see the drop-down arrow when I click the sub-menu item within the sensuctl top-level menu.

**Comment by rnevius** [comment]
@hillaryfraley I'm guessing there's an issue with either the directory/file structure in your test, or the front matter. Is there a way I can see what you've done so that we can pair on this?

**Comment by hillaryfraley** [comment]
@rnevius I kept messing with it and couldn't get it to work, so I deleted everything and started over. I must have done something incorrectly before because it's working according to your instructions, with the sub-menu folder inside the intended top-level menu folder. I'm going to do a little more testing but it looks like this is working as you have it here.

**Review by hillaryfraley — APPROVED** [review]
I tested this by creating an example section of the docs to reproduce the "Monitoring Event Pipeline" section in https://github.com/sensu/sensu-docs/pull/2340. This works! Thank you @rnevius

**Pull request merged**
