### PR TITLE
Update 404 page

### LINKED ISSUE #447: More helpful 404 page
Help users get back on track when they get to the 404 page.

## This is an issue with:

Bug (site functionality or styling)

## Expected Behavior
404 page should be consistent with the rest of the site and help users find what they're looking for.

## Current Behavior
Current 404 page links to the docs homepage.

## Possible Solution
- Add page styling and branding
- Add helpful links
- Add search bar

## Screenshots
screen shot 2018-05-31 at 11 17 38 am

### PR DESCRIPTION
**Pull request by rnevius**
## Description

Adds Algolia search results and a fresher design to the 404 page.

## Motivation and Context

Closes #447

### CODE REVIEW

**Review by hillaryfraley — COMMENTED** [review]
@rnevius this looks great! I'm running it locally from http://localhost:1313/404.html.

My only question is whether there is any way to limit the search options based on the doc set they were using when they hit the 404. For example, if the link that results in a 404 is from https://docs.sensu.io/sensu-go, could the 404 page search be limited to the Sensu Go docs? This is how the regular search works on our site, so I thought it was worth asking.

**Comment by cwjohnston** [comment]
This looks great. +1 for scoping search to Sensu Go product. 



Can we omit the product and version component of the URL?

e.g. visiting https://sensu-docs-update-404-gjegv0as.herokuapp.com/sensu-go/latest/guides/checks

puts `sensu-go latest guides checks` in the search, whereas ideally I think it would be `guides checks`

**Comment by rnevius** [comment]
@hillaryfraley / @cwjohnston – updated!

It took some [hackery](https://github.com/sensu/sensu-docs/pull/2352/commits/d14012babb0b7d7c332eada3038551fccec059b8#diff-85bb8e3591563d3f106add8a8e301405R15) to try to coerce a product/version (since the usual `.Page.Params` for `product` and `version` aren't available on the 404 page), but I think this is acceptable for a 404 page.

**Review by hillaryfraley — APPROVED** [review]
This is so great! Thank you very much, @rnevius

**Review by cwjohnston — APPROVED** [review]

**Pull request merged**
