### PR TITLE
EOL alert color change

### PR DESCRIPTION
**Pull request by hillaryfraley**
Here are a few ideas for changing the EOL alert color at the top of every page in the Core, Enterprise, Enterprise Dashboard, and Uchiwa docs.

The idea is to use a more noticeable color.

- Core: a slightly lighter shade of the color we use in the Sensu Go tile on the docs.sensu.io page
- Enterprise: a slightly darker shade of the Sensu green color used on sensu.io
- Enterprise Dashboard: a darker shade of the red currently used
- Uchiwa: the original red to help compare the other ideas

Any preferences? Any better ideas for color?

### CODE REVIEW

**Comment by hillaryfraley** [comment]
I solicited a vote for the darker red (Enterprise Dashboard) from @Blue0ctober today!

**Comment by cwjohnston** [comment]
Casting my vote for the darker red as well. 👍 🔴

**Review by cwjohnston — CHANGES_REQUESTED** [review]
Please apply #b7312e across all products.

**Comment by hillaryfraley** [comment]
@cwjohnston I updated the color for all EOL bars (across Core, Enterprise, Enterprise Dashboard, and Uchiwa)

**Review by cwjohnston — APPROVED** [review]

**Pull request merged**
