### PR TITLE
Add examples for VaultProvider and vault secrets

### PR DESCRIPTION
**Pull request by echlebek**
This is a partial document that adds examples for VaultProvider, and for secrets that use the VaultProvider.

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@echlebek it seems like this would eventually be merged into https://github.com/sensu/sensu-docs/pull/2122 -- is that correct?

**Review by nikkictl — COMMENTED** [review]
I feel like the context you provide around the examples is very valuable. However I think that information might be more appropriate in reference docs or user guides, rather than api docs which just show each api endpoint. See https://github.com/sensu/sensu-docs/issues/2118, https://github.com/sensu/sensu-docs/issues/2116, and https://github.com/sensu/sensu-docs/issues/2113. @hillaryfraley wdyt?

**Comment by hillaryfraley** [comment]
@nikkixdev @echlebek Is VaultProvider a separate endpoint from Secrets and Provider? I'm not quite clear on that.

**Comment by nikkictl** [comment]
@hillaryfraley a VaultProvider is the same endpoint of a Provider. Similar to AuthProviders, you can use the same endpoints for LDAP and OIDC provider types. With secrets Providers, we have Env and Vault (see `Type` field).

**Comment by hillaryfraley** [comment]
I think this content is covered in https://github.com/sensu/sensu-docs/pull/2126 and https://github.com/sensu/sensu-docs/pull/2125, and partly in https://github.com/sensu/sensu-docs/pull/2122.

**Pull request closed without merging**
